intervalMinutes: 5
maxImagesPerInterval: 1
maxSendAttachmentsPerHour: 2
saveQuality: 75
saveOriginal: false
saveHighlighted: true
saveObjectsCount: 4
saveFacesCount: 4
textAttachments: false
deleteAfterHours: 24
deleteAfterGB: 2
