skip: false
padding: 0
scaleWidth: 320
minPercentage: 2
maxPercentage: 75
maxMotions: 20
overloadPercent: 90
thresholdPercent: 40
noiseReduction: 10
highlightColor: purple
highlightThickness: 3
backgroundHistory: 500
backgroundThreshold: 16
detectShadows: true
closingSize: 3
minMotionFrames: 1
mergeOverlapPercent: 20
mergeDistance: 10
gridSize: 16
